name: Tests

on:
  push:
    branches:
      - dev  # or another branch for your development workflow

jobs:
  test-and-version:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Run tests
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install homeassistant
        pip install pytest pytest-homeassistant-custom-component
        #pip install -r requirements.txt  # If your integration has additional dependencies
        pytest tests/
        continue-on-error: false  # Ensures workflow stops if tests fail

    - name: Update manifest.json with new version
      if: success()
      run: |
        # Update the version in manifest.json
        python scripts/update_manifest_version.py "$version"

    - name: Commit and push updated manifest.json
      if: success()
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add manifest.json
        git commit -m "Update version in manifest.json to $version"
        git push

    - name: Merge to main branch
      if: success()
      run: |
        # Check out main branch and merge changes from the current branch
        git checkout main
        git merge dev --no-ff -m "Merge dev into main after version update"
        git push origin main
