name: Tests

on:
  push:
    branches:
      - main

jobs:
  test-and-version:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Extract version from commit message
      id: extract_version
      run: |
        # Get the first line of the commit message
        COMMIT_MSG=$(git log -1 --pretty=%B | head -n 1)
        
        # Extract version if the message starts with "Version"
        if [[ $COMMIT_MSG =~ Version[[:space:]]([0-9]+\.[0-9]+\.[0-9]+) ]]; then
          VERSION=${BASH_REMATCH[1]}
          echo "version=$VERSION" >> $GITHUB_ENV
        else
          echo "No valid version found in commit message."
          exit 1
        fi

    - name: Update manifest.json with new version
      run: |
        # Update the version in manifest.json
        python scripts/update_manifest_version.py "$version"

    - name: Commit and push updated manifest.json
      if: success()
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add manifest.json
        git commit -m "Update version in manifest.json to $version"
        git push
